version: '3.8'

services:
  # Next.js application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:din@db:5432/fyp
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
    depends_on:
      - db
    networks:
      - app_network

  # PostgreSQL database (if you're using Prisma with PostgreSQL)
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=din
      - POSTGRES_DB=fyp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  # pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=izzuddin6595@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=udin6595
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: 
  pgadmin_data: 