services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: servicefinder-db
    environment:
      POSTGRES_DB: fyp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: din
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - servicefinder-network
    restart: unless-stopped

  # Next.js Application
  app:
    build: .
    container_name: servicefinder-app
    environment:
      DATABASE_URL: "postgresql://postgres:din@postgres:5432/fyp"
      NEXTAUTH_SECRET: "your-nextauth-secret-key-here-change-this"
      NEXTAUTH_URL: "https://servefinder.xyz"  # Changed to HTTPS domain
      NODE_ENV: "production"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - servicefinder-network
    restart: unless-stopped
    volumes:
      - ./public/uploads:/app/public/uploads

volumes:
  postgres_data:

networks:
  servicefinder-network:
    driver: bridge